### ISSUE TITLE
url shortener diskusinya gak bisa diakses

### ISSUE THREAD

**Issue by fajarsulaksono** [an1polimember/anies-sandi-said#3]
padahal redditnya bisa akses

![screen shot 2017-11-24 at 9 14 14 am](https://user-images.githubusercontent.com/202346/33193000-fdc5a9fe-d0f7-11e7-9e87-15d44e7b1b43.png)

**Comment by martheen** [comment]
Work fine in mine (I use Comodo DNS). If you're using hostfile to access reddit, add entry for redd.it (nslookup return 151.101.129.140 for me)

**Comment by an1polimember** [comment]
diambil dari sini
https://www.reddit.com/r/indonesia/comments/5dqam6/for_who_edit_their_etchosts_file/?st=jadkxka6&sh=c02ad6b8
---
#Reputable Sites
151.101.129.140 reddit.com

151.101.129.140 www.reddit.com

151.101.129.140 np.reddit.com

151.101.129.140 bt.reddit.com

151.101.129.140 m.reddit.com

107.23.11.190 out.reddit.com

151.101.129.140 oauth.reddit.com

151.101.45.140 ssl.reddit.com

#bonus for related website

151.101.24.193 imgur.com

151.101.24.193 www.imgur.com

151.101.24.193 i.imgur.com

104.156.81.217 vimeo.com

104.156.81.217 player.vimeo.com

---
post komentar bila anda sudah bisa mengakses link diskusi nya :smile:

**Comment by fajarsulaksono** [comment]
yes udah bisa nambah item di /etc/hosts -> 151.101.129.140 redd.it 👍
